### ISSUE TITLE
Dist folder doesn't exist in browser packages

### ISSUE THREAD

**Issue by wkokgit** [inrupt/solid-client-authn-js#1223]
### Search terms you've used
Bundle - dist 

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
When following the _How to run test apps?_ (browser section) in the readme.md, it gives an error that the dist folder doesn't exists, which in my case is true.

### To Reproduce
Follow the _browser_ section in _How to run test apps?_ in the readme.md, and open http://localhost:3001

### Expected result
Running a test app on http://localhost:3001/

### Actual result
```ERROR in ./src/App.js
Module not found: Error: Can't resolve '../../../../dist/index' in 'C:\Users\------------\solid-client-authn-js\packages\browser\examples\single\bundle\src'
 @ ./src/App.js 35:0-105 38:27-44 62:4-26 76:4-9 85:4-10 94:4-9
 @ ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 236 bytes {0} [built]
i ｢wdm｣: Failed to compile.
```

### Environment
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.42 GB / 15.82 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @babel/core: ^7.8.6 => 7.10.5
    @babel/preset-env: ^7.8.6 => 7.10.4
    @babel/preset-react: ^7.8.3 => 7.10.4
    babel-loader: ^8.0.6 => 8.1.0
    html-loader: ^0.5.5 => 0.5.5
    html-webpack-plugin: ^3.2.0 => 3.2.0
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.14.0 => 16.14.0
    regenerator-runtime: ^0.13.3 => 0.13.7
    webpack: ^4.41.6 => 4.44.0
    webpack-cli: ^3.3.11 => 3.3.12
    webpack-dev-server: ^3.10.3 => 3.11.0
  npmGlobalPackages:
    browserify: 16.2.3
    create-react-app: 2.1.8
    express: 4.17.1
    gulp-cli: 2.1.0
    http-server: 0.12.3
    live-server: 1.2.1
    serve: 11.3.2
    solid-auth-client: 2.5.5
    solid-server: 5.6.4
```

## Additional information
The dist folder isn't build yet or something. Tried to look how to build that but could not find it. 
Also, the core, node, and oidc, folders within packages do have the dist folder.
Might also be a Windows problem.

**Comment by NSeydoux** [comment]
Thanks for reporting this ! I couldn't reproduce on a fresh clone with my Ubuntu machine, so it may indeed be related to Windows. I'll investigate to see if I can find what the issue is. In the meantime, a code snippet is available at https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate/ if it helps. 

Also, if you run `npm run build` at the root of the project, is something like `lerna info run Ran npm script 'build' in '@inrupt/solid-client-authn-browser' in 30.8s:` shown ? Couid you copy-paste the outcome of the command ?

**Comment by wkokgit** [comment]
Yea there are some results including lerna:

```
C:\Users\---\solid-client-authn-js>npm run build

> root@ build C:\Users\---\solid-client-authn-js
> lerna run build

lerna notice cli v4.0.0
lerna info Executing command in 4 packages: "npm run build"
lerna info run Ran npm script 'build' in '@inrupt/oidc-client-ext' in 4.8s:

> @inrupt/oidc-client-ext@1.7.2 build C:\Users\---\solid-client-authn-js\packages\oidc
> rollup --config rollup.config.js

lerna info run Ran npm script 'build' in '@inrupt/solid-client-authn-core' in 8.6s:

> @inrupt/solid-client-authn-core@1.7.2 build C:\Users\---\solid-client-authn-js\packages\core
> tsc -p tsconfig.json

lerna ERR! npm run build exited 1 in '@inrupt/solid-client-authn-browser'
lerna ERR! npm run build stdout:

> @inrupt/solid-client-authn-browser@1.7.2 build C:\Users\---\solid-client-authn-js\packages\browser
> npm run build-module && npm run build-browser


> @inrupt/solid-client-authn-browser@1.7.2 build-module C:\Users\---\solid-client-authn-js\packages\browser
> npm run clean-module && tsc -p tsconfig.json


> @inrupt/solid-client-authn-browser@1.7.2 clean-module C:\Users\---t\solid-client-authn-js\packages\browser
> rm -rf ./dist

lerna ERR! npm run build stderr:
'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @inrupt/solid-client-authn-browser@1.7.2 clean-module: `rm -rf ./dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @inrupt/solid-client-authn-browser@1.7.2 clean-module script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2021-03-29T08_10_12_379Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @inrupt/solid-client-authn-browser@1.7.2 build-module: `npm run clean-module && tsc -p tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @inrupt/solid-client-authn-browser@1.7.2 build-module script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2021-03-29T08_10_12_400Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @inrupt/solid-client-authn-browser@1.7.2 build: `npm run build-module && npm run build-browser`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @inrupt/solid-client-authn-browser@1.7.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2021-03-29T08_10_12_421Z-debug.log
lerna ERR! npm run build exited 1 in '@inrupt/solid-client-authn-browser'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Roaming\npm-cache\_logs\2021-03-29T08_10_12_475Z-debug.log
```

Here is the output of the log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle root@~prebuild: root@
6 info lifecycle root@~build: root@
7 verbose lifecycle root@~build: unsafe-perm in lifecycle true
8 verbose lifecycle root@~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\---\Documents\Master-Project\solid-client-authn-js\node_modules\.bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\---\AppData\Local\Programs\Python\Python36\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Users\---\AppData\Local\Programs\Python\Python36;;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\---\AppData\Local\Microsoft\WindowsApps;C:\Users\---\AppData\Local\GitHubDesktop\bin;C:\Users\---\AppData\Roaming\npm;C:\Users\---\AppData\Local\Microsoft\WindowsApps;C:\Users\---\AppData\Roaming\TinyTeX\bin\win32;C:\Program Files\heroku\bin;C:\Users\---\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\---\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files\OpenSSL-Win64\bin
9 verbose lifecycle root@~build: CWD: C:\Users\---\solid-client-authn-js
10 silly lifecycle root@~build: Args: [ '/d /s /c', 'lerna run build' ]
11 silly lifecycle root@~build: Returned: code: 1  signal: null
12 info lifecycle root@~build: Failed to exec build script
13 verbose stack Error: root@ build: `lerna run build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid root@
15 verbose cwd C:\Users\---\solid-client-authn-js
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error root@ build: `lerna run build`
22 error Exit status 1
23 error Failed at the root@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

but I don't know if that is of any help.

**Comment by NSeydoux** [comment]
That helps a lot, thanks ! Could you run `git fetch`, then `git checkout fix/build-on-windows`, and tell me if the issue is resolved ?

**Comment by wkokgit** [comment]
I think it works! It compiled successfully and I get the following page:

![image](https://user-images.githubusercontent.com/29282335/112815273-6cc51100-9080-11eb-9cd0-c281d5b46c55.png)

One line I saw when running `npm ci` within `packages/browser/examples/single/bundle/` is this one:

`Skipping 'fsevents' build as platform win32 is not supported`, not sure if this will cause problems in the future, but for now it works.

**Comment by NSeydoux** [comment]
I think it means that unlike on Unix systems, if you change the example app the running code won't be updated live, and you'll have to re-run `npm run start`, but I don't think it should be an issue otherwise. I'll merge the changes, cut a release, and update this issue when all is well and you can switch back to the main branch :)
