### ISSUE TITLE
Running the node authentication example does not work

### ISSUE THREAD

**Issue by Laursen79** [inrupt/solid-client-authn-js#3228]
### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [x] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
Running the node authentication [example](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-nodejs-web-server/#example) does not work.
Maybe there is something I have missed, or maybe the documentation should be updated? 
Either way I would appreciate some help.

### To Reproduce

1. Create a folder called **example** and `cd` into it.
2. Create a **server.js** and copy the code from the example into it.
3. Run `npm i @inrupt/solid-client-authn-node express cookie-session`.
4. Run `node server.js`.
5. Open **localhost:3000** in Firefox.
6. Go to **localhost:3000/login** and login using Inrupt.

### Expected result
The server should not crash.

### Actual result
The server crashes with error:
```
/home/simon/example/node_modules/openid-client/lib/helpers/process_response.js:38
      throw new OPError(response.body, response);
            ^

OPError: invalid_grant (redirect_uri mismatch)
    at processResponse (/home/simon/example/node_modules/openid-client/lib/helpers/process_response.js:38:13)
    at Client.grant (/home/simon/example/node_modules/openid-client/lib/client.js:1327:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.callback (/home/simon/example/node_modules/openid-client/lib/client.js:476:24)
    at async AuthCodeRedirectHandler.handle (/home/simon/example/node_modules/@inrupt/solid-client-authn-node/dist/index.js:740:26)
    at async ClientAuthentication.handleIncomingRedirect (/home/simon/example/node_modules/@inrupt/solid-client-authn-node/dist/index.js:115:34)
    at async Session.handleIncomingRedirect (/home/simon/example/node_modules/@inrupt/solid-client-authn-node/dist/index.js:1383:35)
    at async /home/simon/example/server.js:65:3 {
  error: 'invalid_grant',
  error_description: 'redirect_uri mismatch'
}
```

### Environment
```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

  System:
    OS: Linux 6.5 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 7.17 GB / 15.26 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.volta/tools/image/node/18.18.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.8.1 - ~/.volta/tools/image/node/18.18.0/bin/npm
    pnpm: 8.9.0 - ~/.volta/bin/pnpm
  npmPackages:
    @inrupt/solid-client-authn-node: ^1.17.3 => 1.17.3 
    cookie-session: ^2.0.0 => 2.0.0 
    express: ^4.18.2 => 4.18.2 
  npmGlobalPackages:
    corepack: 0.19.0
    npm: 9.8.1
```

**Comment by Laursen79** [comment]
Fixed in the latest update.
